name: "ElytraRace"
main: fr.bakaaless.ElytraRace.plugin.ElytraPlugin
version: 1.0.0
api-version: "1.15"
commands:
  elytrarace:
    aliases:
      - er
    description: "Main command of ElytraRace plugin"